### ISSUE TITLE
Add images to most recent meetings

### ISSUE THREAD

**Issue by WhiteHoodHacker** [sigpwny/sigpwny.com#61]
It would be nice to add some pictures to the most recent meetings to ensure that people have visuals for them. Right now, there are only two places where meeting images are visible:

- [ ] The home (`/`) page: the five most recent meetings are shown (depends on #45)
- [ ] The `/join` page: the first four meetings of the most recent fall semester with a welcome, intro, or beginner tag

Only meetings with the `featured` option will be shown.

Image ideas include finding a frame in the meeting recording that looks good or any other club pictures that look nice. Not against AI-generated images either, you can use your creativity.

If more time is available, images can be added for even more meetings so that way we could look into providing a full card listing view option on the meetings page instead of just a text index.

**Comment by reteps** [comment]
How do you normally screenshot? Just fullscreen youtube and screenshot?
