### ISSUE TITLE
Add missing alumni

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#78]

**Comment by reteps** [comment]
- [ ] Dillon
- [ ] Chris
- [ ] Jesse
- [ ] Josh
- [ ] Faisal
- [ ] Ankur
- [ ] Ian
- [ ] Kuilin
- [ ] Nathan
- [ ] Ravi
- [ ] Thomas
- [ ] Yifei

**Comment by WhiteHoodHacker** [comment]
I also think it would be awesome if we could get people like Parisa or Whitney on the alumni list!

**Comment by reteps** [comment]
also some of these people sent their info on discord, so either I or @WhiteHoodHacker should add them

**Comment by sigpwny-uiuc** [comment]
Nathan can go in and change anything he needs.
