### ISSUE TITLE
Add missing helpers

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#79]
- [x] George
- [x] Juniper
- [x] Kyler
- [x] Sam
- [x] Daniel
- [x] Louis
- [x] Sagnik
- [x] Jake
- [x] Kevin
- [x] Nitya
- [x] Pomona

**Comment by reteps** [comment]
- [ ] George
- [ ] Juniper
- [ ] Kyler
- [ ] Kevin
- [ ] Sam
- [ ] Daniel
- [ ] Louis

**Comment by WhiteHoodHacker** [comment]
https://cms.sigpwny.com/ or fork the repo and you can add your profile manually via `./content/profiles/helpers/`
