### ISSUE TITLE
Align alumni schema on CMS with schema in markdown files

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#84]

**Comment by WhiteHoodHacker** [comment]
I think we've decided to make Helper == Admin schema, correct?

**Comment by reteps** [comment]
i think so, but alumni needs like a "class of" field and stuff right

**Comment by WhiteHoodHacker** [comment]
> i think so, but alumni needs like a "class of" field and stuff right

Yes, alumni have extra fields.

**Comment by reteps** [comment]
right, yifei mentioned to me that the alumni in the files don't have to input a bio but he had to when he did it through cms

**Comment by WhiteHoodHacker** [comment]
Fixed in https://github.com/sigpwny/sigpwny.com/commit/a949957110a419434fda637d58ac062d0499ffb4
