### ISSUE TITLE
Clicking on a meeting reverts scroll

### ISSUE THREAD

**Issue by reteps** [sigpwny/sigpwny.com#86]
if I am on a meeting:
![image](https://github.com/sigpwny/sigpwny.com/assets/13869303/09fce17d-e9a3-4f7a-bf94-ee227fa9cd4e)

and click to a different one, the sidebar scrolls to the top, not to where I previously was.
![image](https://github.com/sigpwny/sigpwny.com/assets/13869303/280ed22c-0fb3-4cfa-83ea-7d81f49db8ef)

**Comment by WhiteHoodHacker** [comment]
This is an issue that I'd likely work on in conjunction with #4 since it would involve setting the sidebar as part of the layout to animate.
